version: '3'

services:
  subaru-dream:
    image: $DOCKER_USER/$APP_NAME
    container_name: $SERVICE_NAME
    restart: unless-stopped
    ports:
      - '2222:80'

networks:
  default:
    external:
      name: golf7-network