version: '3'

services:
  golf7-sale:
    image: ${env.DOCKER_USER}/${env.APP_NAME}:${env.APP_VERSION}
    container_name: $APP_NAME
    restart: unless-stopped
    ports:
      - '2222:80'

networks:
  default:
    external:
      name: golf7-network