version: '3'

services:
  golf7-sale:
    image: ${IMAGE}
    container_name: golf7-sale
    restart: unless-stopped
    ports:
      - '2222:80'

networks:
  default:
    external:
      name: golf7-network